name = "personal-website-api"
main = "index.js"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# D1数据库绑定
[[d1_databases]]
binding = "DB"  # Worker中使用的变量名
database_name = "lyb888-website-db"  # 数据库名称
database_id = "67dfe1a7-3a68-44eb-8086-befc72bc8e1c"  # 数据库ID

[[vars]]
# 这里可以添加环境变量
